services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    volumes:
      - ./backend/app/users.db:/app/app/users.db
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    restart: unless-stopped
